// Quotes data - can be imported by both client and server components
export const quotes = [
    { id: 1, text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { id: 2, text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
    { id: 3, text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
    { id: 4, text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { id: 5, text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
    { id: 6, text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
    { id: 7, text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { id: 8, text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
    { id: 9, text: "If life were predictable it would cease to be life, and be without flavor.", author: "Eleanor Roosevelt" },
    { id: 10, text: "In the end, we only regret the chances we didn't take.", author: "Lewis Carroll" },
    { id: 11, text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { id: 12, text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { id: 13, text: "Two roads diverged in a wood, and I took the one less traveled by.", author: "Robert Frost" },
    { id: 14, text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    { id: 15, text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
    { id: 16, text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
    { id: 17, text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
    { id: 18, text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { id: 19, text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { id: 20, text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { id: 21, text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
    { id: 22, text: "It is never too late to be what you might have been.", author: "George Eliot" },
    { id: 23, text: "Everything has beauty, but not everyone sees it.", author: "Confucius" },
    { id: 24, text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
    { id: 25, text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { id: 26, text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { id: 27, text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
    { id: 28, text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { id: 29, text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
    { id: 30, text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
    { id: 31, text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
    { id: 32, text: "Go confidently in the direction of your dreams! Live the life you've imagined.", author: "Henry David Thoreau" },
    { id: 33, text: "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.", author: "Henry Ford" },
    { id: 34, text: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi" },
    { id: 35, text: "Failure is the condiment that gives success its flavor.", author: "Truman Capote" },
    { id: 36, text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
    { id: 37, text: "What we think, we become.", author: "Buddha" },
    { id: 38, text: "The mind is everything. What you think you become.", author: "Buddha" },
    { id: 39, text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { id: 40, text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
    { id: 41, text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
    { id: 42, text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
    { id: 43, text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { id: 44, text: "The greatest wealth is to live content with little.", author: "Plato" },
    { id: 45, text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
    { id: 46, text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
    { id: 47, text: "Life is 10% what happens to me and 90% of how I react to it.", author: "Charles Swindoll" },
    { id: 48, text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
    { id: 49, text: "Nothing is impossible, the word itself says 'I'm possible'!", author: "Audrey Hepburn" },
    { id: 50, text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
    { id: 51, text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
    { id: 52, text: "The purpose of life is not to be happy. It is to be useful, to be honorable.", author: "Ralph Waldo Emerson" },
    { id: 53, text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
    { id: 54, text: "Life shrinks or expands in proportion to one's courage.", author: "Anaïs Nin" },
    { id: 55, text: "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", author: "Aristotle" },
    { id: 56, text: "Ask and it will be given to you; seek and you will find.", author: "Jesus Christ" },
    { id: 57, text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
    { id: 58, text: "The unexamined life is not worth living.", author: "Socrates" },
    { id: 59, text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
    { id: 60, text: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey" },
    { id: 61, text: "Learn from yesterday, live for today, hope for tomorrow.", author: "Albert Einstein" },
    { id: 62, text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
    { id: 63, text: "Two things are infinite: the universe and human stupidity.", author: "Albert Einstein" },
    { id: 64, text: "I've learned that people will forget what you said, but never how you made them feel.", author: "Maya Angelou" },
    { id: 65, text: "The most common way people give up their power is by thinking they don't have any.", author: "Alice Walker" },
    { id: 66, text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { id: 67, text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
    { id: 68, text: "Certain things catch your eye, but pursue only those that capture the heart.", author: "Ancient Indian Proverb" },
    { id: 69, text: "The person who says it cannot be done should not interrupt the person doing it.", author: "Chinese Proverb" },
    { id: 70, text: "I would rather die of passion than of boredom.", author: "Vincent van Gogh" },
    { id: 71, text: "A truly rich man is one whose children run into his arms when his hands are empty.", author: "Unknown" },
    { id: 72, text: "It is not what you do for your children, but what you have taught them to do for themselves.", author: "Ann Landers" },
    { id: 73, text: "If you want your children to turn out well, spend twice as much time with them.", author: "Abigail Van Buren" },
    { id: 74, text: "Build your own dreams, or someone else will hire you to build theirs.", author: "Farrah Gray" },
    { id: 75, text: "The battles that count aren't the ones for gold medals. They're the ones fought within.", author: "Jesse Owens" },
    { id: 76, text: "Education costs money. But then so does ignorance.", author: "Sir Claus Moser" },
    { id: 77, text: "I have learned over the years that when one's mind is made up, this diminishes fear.", author: "Rosa Parks" },
    { id: 78, text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { id: 79, text: "If you look at what you have in life, you'll always have more.", author: "Oprah Winfrey" },
    { id: 80, text: "Remember that not getting what you want is sometimes a wonderful stroke of luck.", author: "Dalai Lama" },
    { id: 81, text: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
    { id: 82, text: "Dream big and dare to fail.", author: "Norman Vaughan" },
    { id: 83, text: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr." },
    { id: 84, text: "Do what you feel in your heart to be right – for you'll be criticized anyway.", author: "Eleanor Roosevelt" },
    { id: 85, text: "Happiness is not by chance, but by choice.", author: "Jim Rohn" },
    { id: 86, text: "The best way to predict your future is to create it.", author: "Abraham Lincoln" },
    { id: 87, text: "Fall seven times and stand up eight.", author: "Japanese Proverb" },
    { id: 88, text: "Everything has beauty, but not everyone can see.", author: "Confucius" },
    { id: 89, text: "How wonderful it is that nobody need wait a single moment before starting to improve the world.", author: "Anne Frank" },
    { id: 90, text: "When I let go of what I am, I become what I might be.", author: "Lao Tzu" },
    { id: 91, text: "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", author: "Maya Angelou" },
    { id: 92, text: "Happiness is not something readymade. It comes from your own actions.", author: "Dalai Lama" },
    { id: 93, text: "If you're offered a seat on a rocket ship, don't ask what seat! Just get on.", author: "Sheryl Sandberg" },
    { id: 94, text: "First, have a definite, clear practical ideal; a goal, an objective.", author: "Aristotle" },
    { id: 95, text: "If the wind will not serve, take to the oars.", author: "Latin Proverb" },
    { id: 96, text: "You can't fall if you don't climb. But there's no joy in living your whole life on the ground.", author: "Unknown" },
    { id: 97, text: "We must balance conspicuous consumption with conscious capitalism.", author: "Kevin Kruse" },
    { id: 98, text: "Too many of us are not living our dreams because we are living our fears.", author: "Les Brown" },
    { id: 99, text: "Challenges are what make life interesting and overcoming them is what makes life meaningful.", author: "Joshua J. Marine" },
    { id: 100, text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
    { id: 101, text: "I have been impressed with the urgency of doing. Knowing is not enough; we must apply.", author: "Leonardo da Vinci" },
    { id: 102, text: "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.", author: "Jamie Paolinetti" },
    { id: 103, text: "You take your life in your own hands, and what happens? A terrible thing, no one to blame.", author: "Erica Jong" },
    { id: 104, text: "What's money? A man is a success if he gets up in the morning and goes to bed at night.", author: "Bob Dylan" },
    { id: 105, text: "I didn't fail the test. I just found 100 ways to do it wrong.", author: "Benjamin Franklin" },
    { id: 106, text: "In order to succeed, your desire for success should be greater than your fear of failure.", author: "Bill Cosby" },
    { id: 107, text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { id: 108, text: "The person who says it cannot be done should not interrupt the person who is doing it.", author: "Chinese Proverb" },
    { id: 109, text: "There are no traffic jams along the extra mile.", author: "Roger Staubach" },
    { id: 110, text: "It is never too late to be what you might have been.", author: "George Eliot" },
    { id: 111, text: "You become what you believe.", author: "Oprah Winfrey" },
    { id: 112, text: "I would rather die of passion than of boredom.", author: "Vincent van Gogh" },
    { id: 113, text: "A truly rich man is one whose children run into his arms when his hands are empty.", author: "Unknown" },
    { id: 114, text: "It is not what you do for your children, but what you have taught them to do for themselves.", author: "Ann Landers" },
    { id: 115, text: "If you want your children to turn out well, spend twice as much time with them.", author: "Abigail Van Buren" },
    { id: 116, text: "Build your own dreams, or someone else will hire you to build theirs.", author: "Farrah Gray" },
    { id: 117, text: "The battles that count aren't the ones for gold medals.", author: "Jesse Owens" },
    { id: 118, text: "Education costs money. But then so does ignorance.", author: "Sir Claus Moser" },
    { id: 119, text: "I have learned over the years that when one's mind is made up, this diminishes fear.", author: "Rosa Parks" },
    { id: 120, text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { id: 121, text: "Remember that not getting what you want is sometimes a wonderful stroke of luck.", author: "Dalai Lama" },
    { id: 122, text: "Dream big and dare to fail.", author: "Norman Vaughan" },
    { id: 123, text: "Do what you feel in your heart to be right.", author: "Eleanor Roosevelt" },
    { id: 124, text: "Believe in yourself. You are braver than you think.", author: "Unknown" },
    { id: 125, text: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand" },
    { id: 126, text: "A diamond is a chunk of coal that did well under pressure.", author: "Unknown" },
    { id: 127, text: "Everything you can imagine is real.", author: "Pablo Picasso" },
    { id: 128, text: "No masterpiece was ever created by a lazy artist.", author: "Unknown" },
    { id: 129, text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    { id: 130, text: "Winners never quit, and quitters never win.", author: "Vince Lombardi" },
    { id: 131, text: "The harder I work, the luckier I get.", author: "Gary Player" },
    { id: 132, text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
    { id: 133, text: "You learn more from failure than from success.", author: "Unknown" },
    { id: 134, text: "If you are working on something exciting, you don't have to be pushed.", author: "Steve Jobs" },
    { id: 135, text: "People who are crazy enough to think they can change the world, are the ones who do.", author: "Rob Siltanen" },
    { id: 136, text: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Og Mandino" },
    { id: 137, text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
    { id: 138, text: "Knowing is not enough; we must apply. Wishing is not enough; we must do.", author: "Johann Wolfgang Von Goethe" },
    { id: 139, text: "Imagine your life is perfect in every respect; what would it look like?", author: "Brian Tracy" },
    { id: 140, text: "We generate fears while we sit. We overcome them by action.", author: "Dr. Henry Link" },
    { id: 141, text: "Whether you think you can or think you can't, you're right.", author: "Henry Ford" },
    { id: 142, text: "Security is mostly a superstition. Life is either a daring adventure or nothing.", author: "Helen Keller" },
    { id: 143, text: "The man who has confidence in himself gains the confidence of others.", author: "Hasidic Proverb" },
    { id: 144, text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { id: 145, text: "Creativity is intelligence having fun.", author: "Albert Einstein" },
    { id: 146, text: "What you lack in talent can be made up with desire, hustle and giving 110%.", author: "Don Zimmer" },
    { id: 147, text: "Do what you can with all you have, wherever you are.", author: "Theodore Roosevelt" },
    { id: 148, text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { id: 149, text: "Try to be a rainbow in someone's cloud.", author: "Maya Angelou" },
    { id: 150, text: "Do good and good will come to you.", author: "Unknown" },
    { id: 151, text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
    { id: 152, text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
    { id: 153, text: "Change the world by being yourself.", author: "Amy Poehler" },
    { id: 154, text: "Every moment is a fresh beginning.", author: "T.S. Eliot" },
    { id: 155, text: "Never regret anything that made you smile.", author: "Mark Twain" },
    { id: 156, text: "Die with memories, not dreams.", author: "Unknown" },
    { id: 157, text: "Aspire to inspire before we expire.", author: "Unknown" },
    { id: 158, text: "Everything you can imagine is real.", author: "Pablo Picasso" },
    { id: 159, text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
    { id: 160, text: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
    { id: 161, text: "Yesterday you said tomorrow. Just do it.", author: "Nike" },
    { id: 162, text: "I don't need it to be easy, I need it to be worth it.", author: "Lil Wayne" },
    { id: 163, text: "The time is always right to do what is right.", author: "Martin Luther King Jr." },
    { id: 164, text: "When words fail, music speaks.", author: "Hans Christian Andersen" },
    { id: 165, text: "Stay hungry. Stay foolish.", author: "Steve Jobs" },
    { id: 166, text: "Good things come to people who wait, but better things come to those who go out and get them.", author: "Unknown" },
    { id: 167, text: "Don't stop when you're tired. Stop when you're done.", author: "Unknown" },
    { id: 168, text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
    { id: 169, text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
    { id: 170, text: "Little things make big days.", author: "Unknown" },
    { id: 171, text: "It's going to be hard, but hard does not mean impossible.", author: "Unknown" },
    { id: 172, text: "Don't wait for opportunity. Create it.", author: "Unknown" },
    { id: 173, text: "Sometimes we're tested not to show our weaknesses, but to discover our strengths.", author: "Unknown" },
    { id: 174, text: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
    { id: 175, text: "Dream it. Wish it. Do it.", author: "Unknown" },
    { id: 176, text: "Success doesn't just find you. You have to go out and get it.", author: "Unknown" },
    { id: 177, text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown" },
    { id: 178, text: "Dream bigger. Do bigger.", author: "Unknown" },
    { id: 179, text: "Don't stop until you're proud.", author: "Unknown" },
    { id: 180, text: "Work hard in silence, let your success be the noise.", author: "Frank Ocean" },
    { id: 181, text: "Don't dream about success. Work for it.", author: "Unknown" },
    { id: 182, text: "Great things never come from comfort zones.", author: "Unknown" },
    { id: 183, text: "Dream it. Believe it. Build it.", author: "Unknown" },
    { id: 184, text: "Success is what happens after you have survived all your mistakes.", author: "Anora Lee" },
    { id: 185, text: "Don't be afraid to fail. Be afraid not to try.", author: "Unknown" },
    { id: 186, text: "Your limitation—it's only your imagination.", author: "Unknown" },
    { id: 187, text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
    { id: 188, text: "Sometimes later becomes never. Do it now.", author: "Unknown" },
    { id: 189, text: "Great things never come from comfort zones.", author: "Unknown" },
    { id: 190, text: "Dream it. Believe it. Build it.", author: "Unknown" },
    { id: 191, text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
    { id: 192, text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
    { id: 193, text: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry" },
    { id: 194, text: "The only person you should try to be better than is the person you were yesterday.", author: "Unknown" },
    { id: 195, text: "Be so good they can't ignore you.", author: "Steve Martin" },
    { id: 196, text: "Don't practice until you get it right. Practice until you can't get it wrong.", author: "Unknown" },
    { id: 197, text: "Success is a journey, not a destination.", author: "Arthur Ashe" },
    { id: 198, text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
    { id: 199, text: "A year from now you may wish you had started today.", author: "Karen Lamb" },
    { id: 200, text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { id: 201, text: "Don't wait. The time will never be just right.", author: "Napoleon Hill" },
    { id: 202, text: "If people are doubting how far you can go, go so far that you can't hear them anymore.", author: "Michele Ruiz" },
    { id: 203, text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
    { id: 204, text: "A champion is defined not by their wins but by how they can recover when they fall.", author: "Serena Williams" },
    { id: 205, text: "The only way to prove that you're a good sport is to lose.", author: "Ernie Banks" },
    { id: 206, text: "Today's accomplishments were yesterday's impossibilities.", author: "Robert H. Schuller" },
    { id: 207, text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
    { id: 208, text: "You don't need to see the whole staircase, just take the first step.", author: "Martin Luther King Jr." },
    { id: 209, text: "Quality is not an act, it is a habit.", author: "Aristotle" },
    { id: 210, text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { id: 211, text: "Only the paranoid survive.", author: "Andy Grove" },
    { id: 212, text: "It's hard to beat a person who never gives up.", author: "Babe Ruth" },
    { id: 213, text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
    { id: 214, text: "The future belongs to those who prepare for it today.", author: "Malcolm X" },
    { id: 215, text: "If you can dream it, you can do it.", author: "Walt Disney" },
    { id: 216, text: "A winner is a dreamer who never gives up.", author: "Nelson Mandela" },
    { id: 217, text: "Don't let the fear of losing be greater than the excitement of winning.", author: "Robert Kiyosaki" },
    { id: 218, text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { id: 219, text: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
    { id: 220, text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { id: 221, text: "All progress takes place outside the comfort zone.", author: "Michael John Bobak" },
    { id: 222, text: "People who succeed have momentum. The more they succeed, the more they want to succeed.", author: "Tony Robbins" },
    { id: 223, text: "Don't be distracted by criticism. Remember: the only taste of success some people get is to take a bite out of you.", author: "Zig Ziglar" },
    { id: 224, text: "I find that when you have a real interest in life and a curious life, that sleep is not the most important thing.", author: "Martha Stewart" },
    { id: 225, text: "It's not what you look at that matters, it's what you see.", author: "Henry David Thoreau" },
    { id: 226, text: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
    { id: 227, text: "The function of leadership is to produce more leaders, not more followers.", author: "Ralph Nader" },
    { id: 228, text: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
    { id: 229, text: "As we look ahead into the next century, leaders will be those who empower others.", author: "Bill Gates" },
    { id: 230, text: "If you genuinely want something, don't wait for it – teach yourself to be impatient.", author: "Gurbaksh Chahal" },
    { id: 231, text: "The only strategy that is guaranteed to fail is not taking risks.", author: "Mark Zuckerberg" },
    { id: 232, text: "If you're not stubborn, you'll give up on experiments too soon.", author: "Jeff Bezos" },
    { id: 233, text: "I knew that if I failed I wouldn't regret that, but I knew the one thing I might regret is not trying.", author: "Jeff Bezos" }
  ];
